spring:
  profiles: default

  jpa:
    hibernate:
    ddl-auto: create-update
    generate-ddl: false
    show-sql: true

datasource:
    masterDB:
       driver-class-name: "com.mysql.jdbc.Driver"
       url: "jdbc:mysql://52.78.110.20:3306/gamseong?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8"
       username: 'root'
       password: gamseong1234
       initial-size: 10
       max-active: 50
       max-idle: 50
       min-idle: 10
       max-wait: 5000
       connection-test-query: "SELECT 1"
       testWhileIdle: "true"
       minEvictableIdleTimeMillis: "3600000"
       timeBetweenEvictionRunsMillis: "60000"

    slaveDB:
       driver-class-name: "com.mysql.jdbc.Driver"
       url: "jdbc:mysql://52.78.110.20:3306/gamseong?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8"
       username: 'root'
       password: gamseong1234
       initial-size: 10
       max-active: 50
       max-idle: 50
       min-idle: 10
       max-wait: 5000
       connection-test-query: "SELECT 1"
       testWhileIdle: "true"
       minEvictableIdleTimeMillis: "3600000"
       timeBetweenEvictionRunsMillis: "60000"

multipart:
  maxFileSiz: 1MB
  maxRequestSize: 1MB